name: Deploy Web
on:
  push:
    paths:
    - 'apps/web/**'
    pull_request:
      types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ false }} # temporarily pause workflow
    # if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Run build
        run: echo "Build Executed!"
        
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Run build
        run: echo "Lint Executed!"

  deploy_web:
    needs: [build, lint]
    runs-on: ubuntu-latest
    if: ${{ false }} # temporarily pause workflow
    # if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJ_ID }}
          PRODUCTION: false
          ALIAS_DOMAINS: |
            {BRANCH}.turbo-web.vercel.app