name: Deploy Web
on:
  push:
    paths:
    - 'apps/web/**'
    pull_request:
      types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ false }} # temporarily pause workflow
    # if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 14

      - name: Build
        run: yarn turbo run build --scope=web

      - name: Completed!
        run: echo "All runs completed"