name: "Run UI Packages"
on:
  push:
    paths:
    - 'packages/ui/**'
    pull_request:
      types: [opened, synchronize]
jobs:
  console-linux:
    name: Console Linux
    timeout-minutes: 8
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    steps:
      - name: Run echo command
        shell: bash
        run: echo "Actions is working A-Okay for PACKAGES/UI!!"
         
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - run: git status

      - uses: NevetsKuro/Turbo-Template/.github/workflows/run_web
        with:
          gref: ${GITHUB_REF##*/}