name: "Run & Deploy - Docs Apps"
on:
  pull_request:
    types: [opened, synchronize]
    paths:
    - 'apps/docs/**'
  # pull_request_review:
  #   types: [submitted]

jobs:
  build-run-docs:
    name: Run Doc App on linux system
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 14

      - name: Install dependencies
        run: cd apps/docs && yarn

      - run: yarn turbo run build --scope="docs"

      - id: firebase_docs
        # if: ${{ github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DRIP_PROJECTS }}'
          projectId: drip-projects
          target: turbo-docs
          expires: 1d
          channelId: 'preview-doc-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}'

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        if: ${{ github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main' }}
        with:
          message: '👋 Deployed Docs App! URL: ${{steps.firebase_docs.outputs.details_url}}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
