name: "Run UI Packages"
on:
  push:
    paths:
    - 'packages/ui/**'
    pull_request:
      types: [opened, synchronize]
jobs:
  console-ui-packages:
    name: Running UI Packages
    timeout-minutes: 8
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    steps:
      - name: Run echo command
        shell: bash
        run: echo "Actions is working A-Okay for PACKAGES/UI!!"
         
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - run: git status

  console-build-docs:
    name: Running Docs App
    needs: console-ui-packages
    timeout-minutes: 8
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    steps:
      - name: Run echo command
        shell: bash
        run: echo "Actions is working A-Okay for DOCS!!"

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 14

      - name: Checkout branch
        run: |
          git status
          echo "${{ github.event.pull_request }}"
          echo "${{ github.ref }}"

      - name: Install dependencies
        run: cd apps/docs && yarn

      - run: yarn turbo run build --scope="docs"

      - name: Hosting using firebase
        id: firebase_docs
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DRIP_PROJECTS }}'
          projectId: drip-projects
          target: turbo-docs
          expires: 1d
          channelId: 'preview-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}'
      
      - run: 'Deployed! URL: ${{steps.firebase_docs.outputs.details_url}}'

      - run: 'Outputs: ${{github.event.number}}'

      - run: 'Outputs: ${{github.event.pull_request}}'

      - shell: bash
        run: 'node -p 'console.log(${{ github.context }})'

      - name: Comment URL
        uses: actions/github-script@v6
        if: ${{ context.issue.number != ''}}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: github.context.issue.number,
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              body: '👋 Deployed! URL: ${{steps.firebase_docs.outputs.details_url}}'
            })  

  console-build-web:
    name: Running Web app
    needs: console-ui-packages
    timeout-minutes: 8
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    steps:
      - name: Run echo command
        shell: bash
        run: echo "Actions is working A-Okay for WEB!!"

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 14

      - name: Checkout branch
        run: |
          git status
          echo "${{ github.event.pull_request }}"
          echo "${{ github.ref }}"

      - name: Install dependencies
        run: cd apps/web && yarn

      - run: yarn turbo run build --scope="web"

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DRIP_PROJECTS }}'
          projectId: drip-projects
          target: turbo-web
          expires: 1d
          channelId: 'preview-web-${{ github.event.number }}-${{ github.head_ref }}'