name: "Run & Deploy - Web App"
on:
  pull_request:
    types: [opened, synchronize]
    paths:
    - 'apps/web/**'
  # pull_request_review:
  #   types: [submitted]
  #   paths:
  #   - 'apps/web/**'

jobs:
  build-run-web:
    name: Run Web App on linux system
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version: 14

      - name: Install dependencies
        run: cd apps/web && yarn

      - run: yarn turbo run build --scope="web"

      - id: firebase_webs
        # if: ${{ github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DRIP_PROJECTS }}'
          projectId: drip-projects
          target: turbo-web
          expires: 1d
          channelId: 'preview-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}'

      - name: Comment PR
        if: ${{ github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main' }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: '👋 Deployed Web App! URL: ${{steps.firebase_webs.outputs.details_url}}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
