name: "Run Apps - Web"
on:
  push:
    paths:
    - 'apps/web/**'
    pull_request:
      types: [opened, synchronize]
  workflow_run:
    workflows: [Run UI Packages]
    types:
      - completed
jobs:
  console-linux:
    name: Console Linux
    timeout-minutes: 8
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Run echo command
        shell: bash
        run: echo "Started to deploy WEB!!"
      - uses: actions/checkout@v2
      - run: yarn turbo run build --scope="web"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DRIP_PROJECTS }}'
          projectId: drip-projects

  # console-windows:
  #   name: Console Windows
  #   timeout-minutes: 8
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: []
  #   steps:
  #     - name: Run echo command
  #       shell: bash
  #       run: echo "Actions is working A-Okay for WEB!!"